development: &postgres
  adapter: postgresql
  encoding: unicode
  database: TCNS
  pool: 25
  username: postgres
  password: tray#ram1#

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: tray#ram1#