# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02ae9a4367b6c7cc1dc601c1b5d54082421fca10f1a82602a25697d3f8f9176f2a774d0702b19fbda9ddf814b36cf395a46217221b74d796b1aa0a25c9494623

test:
  secret_key_base: 92b847e828916e160bb59cdf1560064e20eab11f6d6c4af7e21aca10f4ab18ebe9c843074038c5651e088a05a120cbe03a73f5b7d2c6869bc166ad64d897a313

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
